{"uuid": "9ac60fcc-556a-4b1f-a9d4-b9f49083d277", "children": ["9598b04a-7b81-4a03-bd16-7dd6aa4ecd77", "b1ed2fb6-4b13-4d21-ad84-2c4c3ebffa49", "a1b9c8fb-183d-43dc-9e5a-a20d763a7b28", "6762eb6f-4a59-4cf6-943f-b682f1b1e864", "a3d8cf68-cb22-4343-ab28-1ebc466e51e6", "67b1bf98-c0e0-41bb-bd28-6712cdbb4d8b", "7adc9e46-5fec-4848-b743-8cfaf43c893f"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"D:\\t\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\t\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\t\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\Desktop\\test\\系统设置\\系统管理设置\\选项表单管理\\test_ERP分类集合.py\", line 708, in login\n    raise e\n  File \"C:\\Users\\Administrator\\Desktop\\test\\系统设置\\系统管理设置\\选项表单管理\\test_ERP分类集合.py\", line 681, in login\n    captcha_data = captcha_img.get_attribute(\"src\").split(\",\")[1]\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^\n"}, "attachments": [{"name": "登录失败截图", "source": "a96924ac-251b-4b9f-b7ba-988f3505a4b0-attachment.png", "type": "image/png"}], "start": 1753514189373, "stop": 1753514191563}], "start": 1753514189373, "stop": 1753514192147}