{"uuid": "06828e74-aa96-4237-af66-565e812196a3", "children": ["931818a9-a4f5-47f0-84a7-e56bb663f255"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"D:\\t\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\t\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\t\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Administrator\\Desktop\\test\\test_招聘审批流程.py\", line 76, in login\n    raise e\n  File \"C:\\Users\\Administrator\\Desktop\\test\\test_招聘审批流程.py\", line 54, in login\n    captcha_data = captcha_img.get_attribute(\"src\").split(\",\")[1]\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^\n"}, "attachments": [{"name": "登录失败截图", "source": "2021a65c-ab06-4108-8d5d-f84d53e9a3e5-attachment.png", "type": "image/png"}], "start": 1753511784784, "stop": 1753511787162}], "start": 1753511784784, "stop": 1753511789288}