{"uuid": "c8b5a21c-7751-4433-8675-518ceb23a449", "children": ["b2acb218-6d07-4c63-b6de-7f013d4ac975"], "befores": [{"name": "cleanup", "status": "passed", "start": 1753511068433, "stop": 1753511068433}], "afters": [{"name": "cleanup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: <unknown>: Failed to read the 'localStorage' property from 'Window': Storage is disabled inside 'data:' URLs.\n  (Session info: chrome=86.0.4240.198)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x006BC013+3194899]\n\tOrdinal0 [0x005A6021+2056225]\n\tOrdinal0 [0x0043F608+587272]\n\tOrdinal0 [0x0044176E+595822]\n\tOrdinal0 [0x00441673+595571]\n\tOrdinal0 [0x00441D5D+597341]\n\tOrdinal0 [0x003EA30C+238348]\n\tOrdinal0 [0x003DFD73+195955]\n\tOrdinal0 [0x003E9B22+236322]\n\tOrdinal0 [0x003DFC1B+195611]\n\tOrdinal0 [0x003C3B7F+80767]\n\tOrdinal0 [0x003C4B4E+84814]\n\tOrdinal0 [0x003C4AD9+84697]\n\tOrdinal0 [0x005BCE64+2149988]\n\tGetHandleVerifier [0x0082BE95+1400773]\n\tGetHandleVerifier [0x0082BB61+1399953]\n\tGetHandleVerifier [0x008331FA+1430314]\n\tGetHandleVerifier [0x0082C69F+1402831]\n\tOrdinal0 [0x005B3D61+2112865]\n\tOrdinal0 [0x005BE5CB+2155979]\n\tOrdinal0 [0x005BE6F5+2156277]\n\tOrdinal0 [0x005CF26E+2224750]\n\tBaseThreadInitThunk [0x76EFFCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77D582AE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77D5827E+238]\n\n", "trace": "  File \"D:\\t\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"D:\\test\\conftest.py\", line 9, in cleanup\n    driver.execute_script(\"window.localStorage.clear();\")\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 551, in execute_script\n    return self.execute(command, {\"script\": script, \"args\": converted_args})[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"D:\\t\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1753511068435, "stop": 1753511068459}], "start": 1753511068433, "stop": 1753511068459}